import 'selection.dart';
import 'weights.dart';

const packageName = 'phosphor_icons_flutter';

String _header(String version) => '''
// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/generate.dart from @phosphor-icons/web $version.
// Icons: Phosphor Icons (https://phosphoricons.com), MIT License.
''';

String _hex(int code) =>
    '0x${code.toRadixString(16).toUpperCase().padLeft(4, '0')}';

/// Source of `lib/src/phosphor_icons_<weight>.dart` (unformatted).
String renderWeightFile(
    Weight weight, List<IconEntry> entries, String version) {
  final out = StringBuffer()
    ..writeln(_header(version))
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln("const String _family = '${weight.fontFamily}';")
    ..writeln("const String _package = '$packageName';")
    ..writeln()
    // Flutter's icon tree shaker only subsets fonts it finds at least one
    // const IconData for; any other font ships whole (~500 KB). This one
    // retained glyph makes an unused weight shrink to ~1 KB instead.
    ..writeln(
        '// Keeps this font visible to the icon tree shaker even when the '
        'app uses no')
    ..writeln('// icon of this weight, so the font is cut to one glyph instead '
        'of shipping whole.')
    ..writeln("@pragma('vm:entry-point')")
    ..writeln('const IconData _treeShakeAnchor = '
        'IconData(${_hex(entries.first.codepoint)}, fontFamily: _family, fontPackage: _package);')
    ..writeln()
    ..writeln('/// Phosphor icons in the ${weight.name} weight '
        '(font family `${weight.fontFamily}`).')
    ..writeln('///')
    ..writeln(
        '/// Every member is a `const` [IconData], so release builds only '
        'keep the glyphs')
    ..writeln('/// you reference: `Icon(${weight.className}.acorn)`.')
    ..writeln('abstract final class ${weight.className} {');

  for (final e in entries) {
    out
      ..writeln('  /// Phosphor `${e.kebab}`, ${weight.name} weight.')
      ..writeln('  static const IconData ${e.constant} = '
          'IconData(${_hex(e.codepoint)}, fontFamily: _family, fontPackage: _package);')
      ..writeln();
    for (final alias in e.aliases) {
      out
        ..writeln('  /// Alias of [${e.constant}], ${weight.name} weight.')
        ..writeln('  static const IconData $alias = ${e.constant};')
        ..writeln();
    }
  }

  out
    ..writeln('  /// Every icon in this weight keyed by constant name '
        '(aliases excluded).')
    ..writeln('  ///')
    ..writeln('  /// Referencing this map keeps every glyph of '
        '`${weight.fontFamily}` in release')
    ..writeln('  /// builds; use it for pickers and galleries, not for '
        'looking up a single icon.')
    ..writeln('  static const Map<String, IconData> values = {');
  for (final e in entries) {
    out.writeln("    '${e.constant}': ${e.constant},");
  }
  out
    ..writeln('  };')
    ..writeln('}');
  return out.toString();
}

/// Source of `lib/src/phosphor_icons.dart` (unformatted).
String renderStyleFile(String version) {
  final out = StringBuffer()
    ..writeln(_header(version))
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln();
  for (final w in Weight.values) {
    out.writeln("import 'phosphor_icons_${w.name}.dart';");
  }
  out
    ..writeln()
    ..writeln('/// The Phosphor weights shipped by this package.')
    ..writeln('enum PhosphorIconsStyle {');
  for (final w in Weight.values) {
    out
      ..writeln('  /// [${w.className}], font family `${w.fontFamily}`.')
      ..writeln('  ${w.name},');
  }
  out
    ..writeln(';')
    ..writeln()
    ..writeln('  /// Every icon of this weight keyed by constant name.')
    ..writeln('  ///')
    ..writeln('  /// Calling this keeps the whole font in release builds; '
        'see `values` on the')
    ..writeln('  /// weight classes.')
    ..writeln('  Map<String, IconData> get icons => switch (this) {');
  for (final w in Weight.values) {
    out.writeln(
        '        PhosphorIconsStyle.${w.name} => ${w.className}.values,');
  }
  out
    ..writeln('      };')
    ..writeln('}');
  return out.toString();
}
