// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by tool/generate.dart from @phosphor-icons/web 2.1.2.
// Icons: Phosphor Icons (https://phosphoricons.com), MIT License.

import 'package:flutter/widgets.dart';

import 'phosphor_icons_thin.dart';
import 'phosphor_icons_light.dart';
import 'phosphor_icons_regular.dart';
import 'phosphor_icons_bold.dart';
import 'phosphor_icons_fill.dart';

/// The Phosphor weights shipped by this package.
enum PhosphorIconsStyle {
  /// [PhosphorIconsThin], font family `Phosphor-Thin`.
  thin,

  /// [PhosphorIconsLight], font family `Phosphor-Light`.
  light,

  /// [PhosphorIconsRegular], font family `Phosphor-Regular`.
  regular,

  /// [PhosphorIconsBold], font family `Phosphor-Bold`.
  bold,

  /// [PhosphorIconsFill], font family `Phosphor-Fill`.
  fill,
  ;

  /// Every icon of this weight keyed by constant name.
  ///
  /// Calling this keeps the whole font in release builds; see `values` on the
  /// weight classes.
  Map<String, IconData> get icons => switch (this) {
        PhosphorIconsStyle.thin => PhosphorIconsThin.values,
        PhosphorIconsStyle.light => PhosphorIconsLight.values,
        PhosphorIconsStyle.regular => PhosphorIconsRegular.values,
        PhosphorIconsStyle.bold => PhosphorIconsBold.values,
        PhosphorIconsStyle.fill => PhosphorIconsFill.values,
      };
}
